import BetterSqlite3 from "better-sqlite3";
import { randomUUID } from "node:crypto";
import type { ReasoningEffort, RequirementsSnapshot, ReviewModelConfig, ReviewRunDto, ReviewStatus, ReviewTarget } from "../../shared/contracts";
import { countsAsCompletedReviewRound } from "../reviews/completedRounds";
import { branchModel, configuredModel, DEFAULT_MCP_MODEL, DEFAULT_REVIEW_MODEL } from "./modelSettings";

export interface RepositoryRecord { id: string; path: string; canonical_path: string; display_name: string; git_common_dir: string | null; base_branch: string | null; enabled: number; created_at: string; updated_at: string }
export interface SessionLinkRecord { repository_id: string; thread_id: string; thread_name: string; source_kind: string; last_verified_at: string | null; created_at: string; updated_at: string }
export type RequirementRecord = { id: string; file_path: string; canonical_path: string; file_name: string; last_sha256: string; last_size_bytes: number; last_loaded_at: string; content: string | null; created_at: string; updated_at: string };

export class Database {
  private readonly db: BetterSqlite3.Database;
  constructor(path: string) { this.db = new BetterSqlite3(path); this.db.pragma("journal_mode = WAL"); this.db.pragma("foreign_keys = ON"); this.migrate(); }
  private migrate() { this.db.exec(`
    CREATE TABLE IF NOT EXISTS repositories (id TEXT PRIMARY KEY, path TEXT NOT NULL, canonical_path TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, git_common_dir TEXT, base_branch TEXT, enabled INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS session_links (repository_id TEXT PRIMARY KEY, thread_id TEXT NOT NULL UNIQUE, thread_name TEXT NOT NULL, source_kind TEXT NOT NULL DEFAULT 'appServer', last_verified_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(repository_id) REFERENCES repositories(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS review_runs (id TEXT PRIMARY KEY, repository_id TEXT NOT NULL, thread_id TEXT, turn_id TEXT, target_type TEXT NOT NULL, target_json TEXT NOT NULL, branch TEXT, base_branch TEXT, head_sha TEXT NOT NULL, dirty_at_start INTEGER NOT NULL, requirements_path TEXT NOT NULL, requirements_file_name TEXT NOT NULL, requirements_sha256 TEXT NOT NULL, requirements_snapshot TEXT NOT NULL, requirements_size_bytes INTEGER NOT NULL, requirements_loaded_at TEXT NOT NULL, status TEXT NOT NULL, result_class TEXT NOT NULL DEFAULT 'unknown', result_text TEXT, partial_text TEXT, error_code TEXT, error_text TEXT, tokens_before INTEGER, tokens_after INTEGER, tokens_used INTEGER, token_complete INTEGER NOT NULL DEFAULT 0, model TEXT, reasoning_effort TEXT, started_at TEXT, completed_at TEXT, created_at TEXT NOT NULL, FOREIGN KEY(repository_id) REFERENCES repositories(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS token_snapshots (id INTEGER PRIMARY KEY AUTOINCREMENT, thread_id TEXT NOT NULL, turn_id TEXT, epoch INTEGER NOT NULL, total_tokens INTEGER NOT NULL, input_tokens INTEGER, output_tokens INTEGER, cached_input_tokens INTEGER, recorded_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS review_requirements (id TEXT PRIMARY KEY CHECK(id='global-default'), file_path TEXT NOT NULL, canonical_path TEXT NOT NULL, file_name TEXT NOT NULL, last_sha256 TEXT NOT NULL, last_size_bytes INTEGER NOT NULL, last_loaded_at TEXT NOT NULL, content TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value_json TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS branch_review_settings (repository_id TEXT NOT NULL, branch TEXT NOT NULL, model TEXT NOT NULL, reasoning_effort TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(repository_id, branch), FOREIGN KEY(repository_id) REFERENCES repositories(id) ON DELETE CASCADE);
    CREATE INDEX IF NOT EXISTS review_runs_repository_created ON review_runs(repository_id, created_at DESC);
  `); const columns = new Set((this.db.prepare("PRAGMA table_info(review_runs)").all() as Array<{ name: string }>).map((column) => column.name)); if (!columns.has("model")) this.db.exec("ALTER TABLE review_runs ADD COLUMN model TEXT"); if (!columns.has("reasoning_effort")) this.db.exec("ALTER TABLE review_runs ADD COLUMN reasoning_effort TEXT"); if (!columns.has("repository_key")) this.db.exec("ALTER TABLE review_runs ADD COLUMN repository_key TEXT"); const requirementColumns = new Set((this.db.prepare("PRAGMA table_info(review_requirements)").all() as Array<{ name: string }>).map((column) => column.name)); if (!requirementColumns.has("content")) this.db.exec("ALTER TABLE review_requirements ADD COLUMN content TEXT"); this.db.exec("CREATE INDEX IF NOT EXISTS review_runs_identity_branch_created ON review_runs(repository_key,branch,created_at DESC)"); }
  close() { this.db.close(); }
  listRepositories(): RepositoryRecord[] { return this.db.prepare("SELECT * FROM repositories WHERE enabled=1 ORDER BY created_at").all() as RepositoryRecord[]; }
  getRepository(id: string): RepositoryRecord | undefined { return this.db.prepare("SELECT * FROM repositories WHERE id=?").get(id) as RepositoryRecord | undefined; }
  addRepository(canonicalPath: string, displayName: string, gitCommonDir: string): RepositoryRecord { const now = new Date().toISOString(); const id = randomUUID(); this.db.prepare("INSERT INTO repositories VALUES(?,?,?,?,?,NULL,1,?,?)").run(id, canonicalPath, canonicalPath, displayName, gitCommonDir, now, now); return this.getRepository(id)!; }
  removeRepository(id: string) { this.db.prepare("UPDATE repositories SET enabled=0,updated_at=? WHERE id=?").run(new Date().toISOString(), id); }
  renameRepository(id: string, name: string) { this.db.prepare("UPDATE repositories SET display_name=?,updated_at=? WHERE id=?").run(name, new Date().toISOString(), id); }
  updateBaseBranch(id: string, base: string | null) { this.db.prepare("UPDATE repositories SET base_branch=?,updated_at=? WHERE id=?").run(base, new Date().toISOString(), id); }
  getSetting<T>(key: string): T | undefined { const row = this.db.prepare("SELECT value_json FROM settings WHERE key=?").get(key) as { value_json: string } | undefined; return row ? JSON.parse(row.value_json) as T : undefined; }
  setSetting(key: string, value: unknown) { this.db.prepare("INSERT INTO settings(key,value_json,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at").run(key, JSON.stringify(value), new Date().toISOString()); }
  getDefaultReviewModel(): ReviewModelConfig { return configuredModel(this.getSetting<ReviewModelConfig>("defaultReviewModel"), DEFAULT_REVIEW_MODEL); }
  getDefaultMcpModel(): ReviewModelConfig { return configuredModel(this.getSetting<ReviewModelConfig>("defaultMcpModel"), DEFAULT_MCP_MODEL); }
  saveDefaultReviewModel(config: ReviewModelConfig) { this.setSetting("defaultReviewModel", config); }
  saveDefaultMcpModel(config: ReviewModelConfig) { this.setSetting("defaultMcpModel", config); }
  getBranchReviewConfig(repositoryId: string, branch: string | null): ReviewModelConfig { if (!branch) return this.getDefaultReviewModel(); const row = this.db.prepare("SELECT model,reasoning_effort FROM branch_review_settings WHERE repository_id=? AND branch=?").get(repositoryId, branch) as { model: string; reasoning_effort: ReasoningEffort } | undefined; return branchModel(row ? { model: row.model, reasoningEffort: row.reasoning_effort } : undefined, this.getDefaultReviewModel()); }
  saveBranchReviewConfig(repositoryId: string, branch: string, config: ReviewModelConfig) { this.db.prepare("INSERT INTO branch_review_settings(repository_id,branch,model,reasoning_effort,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(repository_id,branch) DO UPDATE SET model=excluded.model,reasoning_effort=excluded.reasoning_effort,updated_at=excluded.updated_at").run(repositoryId, branch, config.model, config.reasoningEffort, new Date().toISOString()); }
  completedReviewRounds(repositoryKey: string | undefined, branch: string | null): number { if (!repositoryKey || !branch) return 0; return this.listReviewRunsByIdentity(repositoryKey, branch).filter((run) => countsAsCompletedReviewRound(run.status)).length; }
  getSessionLink(repositoryId: string): SessionLinkRecord | undefined { return this.db.prepare("SELECT * FROM session_links WHERE repository_id=?").get(repositoryId) as SessionLinkRecord | undefined; }
  saveSessionLink(repositoryId: string, threadId: string, threadName: string) { const now = new Date().toISOString(); this.db.prepare(`INSERT INTO session_links(repository_id,thread_id,thread_name,source_kind,last_verified_at,created_at,updated_at) VALUES(?,?,?,'appServer',?,?,?) ON CONFLICT(repository_id) DO UPDATE SET thread_id=excluded.thread_id,thread_name=excluded.thread_name,last_verified_at=excluded.last_verified_at,updated_at=excluded.updated_at`).run(repositoryId, threadId, threadName, now, now, now); }
  deleteSessionLink(repositoryId: string) { this.db.prepare("DELETE FROM session_links WHERE repository_id=?").run(repositoryId); }
  saveRequirements(snapshot: RequirementsSnapshot) { const now = new Date().toISOString(); this.db.prepare(`INSERT INTO review_requirements(id,file_path,canonical_path,file_name,last_sha256,last_size_bytes,last_loaded_at,content,created_at,updated_at) VALUES('global-default',?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET file_path=excluded.file_path,canonical_path=excluded.canonical_path,file_name=excluded.file_name,last_sha256=excluded.last_sha256,last_size_bytes=excluded.last_size_bytes,last_loaded_at=excluded.last_loaded_at,content=excluded.content,updated_at=excluded.updated_at`).run(snapshot.path, snapshot.path, snapshot.fileName, snapshot.sha256, snapshot.sizeBytes, snapshot.loadedAt, snapshot.content, now, now); }
  getRequirements(): RequirementRecord | undefined { return this.db.prepare("SELECT * FROM review_requirements WHERE id='global-default'").get() as RequirementRecord | undefined; }
  createReviewRun(data: { repositoryId: string; repositoryKey: string; target: ReviewTarget; branch: string | null; baseBranch: string | null; headSha: string; dirty: boolean; requirements: RequirementsSnapshot; model: ReviewModelConfig; tokensBefore?: number }): ReviewRunDto {
    const id = randomUUID(), now = new Date().toISOString();
    this.db.prepare(`INSERT INTO review_runs(id,repository_id,repository_key,target_type,target_json,branch,base_branch,head_sha,dirty_at_start,requirements_path,requirements_file_name,requirements_sha256,requirements_snapshot,requirements_size_bytes,requirements_loaded_at,status,tokens_before,model,reasoning_effort,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id, data.repositoryId, data.repositoryKey, data.target.type, JSON.stringify(data.target), data.branch, data.baseBranch, data.headSha, data.dirty ? 1 : 0, data.requirements.path, data.requirements.fileName, data.requirements.sha256, data.requirements.content, data.requirements.sizeBytes, data.requirements.loadedAt, "starting", data.tokensBefore ?? null, data.model.model, data.model.reasoningEffort, now);
    return this.getReviewRun(id)!;
  }
  updateReviewRun(id: string, values: Record<string, unknown>) { const allowed = new Set(["thread_id","turn_id","status","result_class","result_text","partial_text","error_code","error_text","tokens_before","tokens_after","tokens_used","token_complete","started_at","completed_at"]); const entries = Object.entries(values).filter(([key]) => allowed.has(key)); if (!entries.length) return; this.db.prepare(`UPDATE review_runs SET ${entries.map(([key]) => `${key}=?`).join(",")} WHERE id=?`).run(...entries.map(([, value]) => value), id); }
  getReviewRun(id: string): ReviewRunDto | undefined { const row = this.db.prepare("SELECT * FROM review_runs WHERE id=?").get(id) as Record<string, unknown> | undefined; return row ? this.mapRun(row) : undefined; }
  getReviewRunByTurnId(turnId: string): ReviewRunDto | undefined { const row = this.db.prepare("SELECT * FROM review_runs WHERE turn_id=? ORDER BY created_at DESC LIMIT 1").get(turnId) as Record<string, unknown> | undefined; return row ? this.mapRun(row) : undefined; }
  listReviewRuns(repositoryId?: string): ReviewRunDto[] { const rows = repositoryId ? this.db.prepare("SELECT * FROM review_runs WHERE repository_id=? ORDER BY created_at DESC").all(repositoryId) : this.db.prepare("SELECT * FROM review_runs ORDER BY created_at DESC").all(); return (rows as Record<string, unknown>[]).map((r) => this.mapRun(r)); }
  listReviewRunsByIdentity(repositoryKey: string, branch: string): ReviewRunDto[] { const rows = this.db.prepare("SELECT * FROM review_runs WHERE repository_key=? AND branch=? ORDER BY created_at DESC").all(repositoryKey, branch); return (rows as Record<string, unknown>[]).map((r) => this.mapRun(r)); }
  latestRun(repositoryId: string): ReviewRunDto | undefined { return this.listReviewRuns(repositoryId)[0]; }
  recoverInterrupted() { this.db.prepare("UPDATE review_runs SET status='recovering' WHERE status IN ('starting','reviewing','waiting_for_approval')").run(); }
  addTokenSnapshot(threadId: string, turnId: string | null, epoch: number, total: number, input?: number, output?: number, cached?: number) { this.db.prepare("INSERT INTO token_snapshots(thread_id,turn_id,epoch,total_tokens,input_tokens,output_tokens,cached_input_tokens,recorded_at) VALUES(?,?,?,?,?,?,?,?)").run(threadId, turnId, epoch, total, input ?? null, output ?? null, cached ?? null, new Date().toISOString()); }
  latestThreadToken(threadId: string): { total_tokens: number; epoch: number } | undefined { return this.db.prepare("SELECT total_tokens,epoch FROM token_snapshots WHERE thread_id=? ORDER BY id DESC LIMIT 1").get(threadId) as { total_tokens: number; epoch: number } | undefined; }
  managerTokens(): number { return (this.db.prepare("SELECT COALESCE(SUM(tokens_used),0) total FROM review_runs").get() as { total: number }).total; }
  repositoryTokens(id: string): number { return (this.db.prepare("SELECT COALESCE(SUM(tokens_used),0) total FROM review_runs WHERE repository_id=?").get(id) as { total: number }).total; }
  private mapRun(row: Record<string, unknown>): ReviewRunDto { return { id: String(row.id), repositoryId: String(row.repository_id), repositoryKey: row.repository_key ? String(row.repository_key) : undefined, threadId: row.thread_id ? String(row.thread_id) : undefined, turnId: row.turn_id ? String(row.turn_id) : undefined, targetType: row.target_type as ReviewTarget["type"], branch: row.branch ? String(row.branch) : undefined, baseBranch: row.base_branch ? String(row.base_branch) : undefined, headSha: String(row.head_sha), dirtyAtStart: Boolean(row.dirty_at_start), requirementsPath: String(row.requirements_path), requirementsFileName: String(row.requirements_file_name), requirementsSha256: String(row.requirements_sha256), requirementsSnapshot: String(row.requirements_snapshot), status: row.status as ReviewStatus, resultClass: row.result_class as ReviewRunDto["resultClass"], resultText: row.result_text ? String(row.result_text) : undefined, partialText: row.partial_text ? String(row.partial_text) : undefined, errorText: row.error_text ? String(row.error_text) : undefined, tokensUsed: row.tokens_used == null ? undefined : Number(row.tokens_used), tokenComplete: Boolean(row.token_complete), model: row.model ? String(row.model) : undefined, reasoningEffort: row.reasoning_effort ? String(row.reasoning_effort) as ReasoningEffort : undefined, startedAt: row.started_at ? String(row.started_at) : undefined, completedAt: row.completed_at ? String(row.completed_at) : undefined, createdAt: String(row.created_at) }; }
}
